[package]
name = "gabalah"
version = "0.1.0"
edition = "2021"

[lib]
name = "gabalah"
path = "src/lib.rs"

[[test]]
name = "ops"
path = "tests/ops.rs"

[dependencies]
byteorder = "1"
env_logger = "0.10"
error-iter = "0.4"
getrandom = "0.2"
clipline = "0.1.1"
log = "0.4"
pixels = "0.15"
randomize = "3"
winit = "0.29"
winit_input_helper = "0.15"
